### PR TITLE
Crystal 0.25.0 support

### PR DESCRIPTION
**Pull request by mamantoha**

### CODE REVIEW

**Comment by faustinoaq** [comment]
Hi @samueleaton can you check this pls? :sweat_smile: 

Crystal 0.25.0 was released and many shards dependencies have been failing :sweat:

**Comment by samueleaton** [comment]
Was away on a week long vacation. will update this today.

**Comment by samueleaton** [comment]
Oh whoops I thought this was an Issue and not a PR lol. I will revert mine real quick and merge this. 😂

**Comment by faustinoaq** [comment]
@samueleaton also remember to release a minor release v0.3.0 (no patch) to avoid breaking-changes issues on projects using `~> 0.2.0`

**Pull request merged**
